var first = document.getElementById("cnt1");
var second = document.getElementById("cnt2");
var elements = document.getElementsByClassName("draw");
var logo = document.getElementById("img");

    first.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia in recusandae magni dicta, neque nostrum cupiditate natus! Accusantium reprehenderit sint temporibus, iste facilis reiciendis autem eligendi nam quod, laborum quae cumque unde molestiae in qui asperiores saepe illo voluptatem tenetur eveniet! Quod sequi repellat aut, facilis, error veniam blanditiis doloremque ipsa consequatur animi porro sunt quo voluptatem reiciendis quisquam, nulla officia at illum. Sunt ab totam exercitationem aliquid voluptatibus quidem, ipsa ea vero eius repellat tempora culpa nemo inventore ipsum. Distinctio saepe quisquam in vitae magni excepturi vero et laborum. Molestiae quibusdam aperiam cupiditate deleniti tempore rerum tenetur quae maiores.";
    second.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi esse sequi quibusdam, non quo quia iure tempore praesentium adipisci deleniti! Dolore autem atque iste reiciendis sit accusantium similique consectetur in vitae architecto, error quis explicabo itaque, facere, nam libero, sequi iure. Sed alias libero veniam officia amet expedita, praesentium laboriosam natus saepe impedit consequuntur vel deserunt esse sint optio nobis, nemo voluptate nisi laudantium cupiditate? Dolore officiis veniam atque cupiditate, aperiam minus culpa, quisquam, nemo ratione debitis laborum natus repellat eos! Et excepturi error, natus unde adipisci officiis eos magnam dolores quia totam, odio vero quae. Culpa sed architecto alias natus perferendis debitis ut incidunt, esse quae asperiores enim eaque eius ad aliquid fugit dolorem quidem voluptatum rem iste atque eveniet illo nobis saepe commodi veniam. Hic nostrum facilis, tenetur quia laboriosam magni sunt quam amet dolorem distinctio explicabo suscipit quos molestias! Rerum optio repellat recusandae numquam iusto labore quidem similique, pariatur, mollitia accusantium officiis eligendi fuga, dolorem suscipit libero adipisci sequi perferendis excepturi soluta consectetur enim voluptatum quam eveniet voluptatem. Quisquam in natus laborum placeat, unde repellendus officia beatae. Possimus a accusamus sunt officia molestias alias aut, officiis fugit animi repudiandae porro harum laudantium voluptas ducimus quae veritatis nemo?";

elements[0].addEventListener("click", function() {
    first.innerHTML = "Projekty";
    second.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum, illo! Consectetur fuga, et laudantium ea eius ex ut nemo amet, aliquid, reprehenderit tempora ab porro eum consequuntur. Doloremque reiciendis aut rerum optio praesentium. Dolores qui eius ab consequatur, totam eveniet optio rem, sit magni suscipit aspernatur esse numquam porro in minus adipisci enim impedit odio ducimus asperiores vitae facilis aliquid! Culpa distinctio eaque dignissimos temporibus odio nihil quis dicta cupiditate odit officia dolorum repellendus aliquid ad perferendis quaerat autem a nemo placeat enim quod, laudantium eveniet repellat corporis nostrum! Obcaecati eos minima nemo iusto eum molestias numquam veritatis sed, reprehenderit iste, ad praesentium non, corrupti esse adipisci porro voluptatibus magnam! Quis cumque culpa magni, eveniet tempore voluptatibus, accusantium dolore ea eos eum repudiandae debitis! Sapiente consequuntur est aperiam dicta blanditiis enim minima reprehenderit itaque voluptatibus, libero aspernatur ut ullam ab vero vel, nisi quis. Id adipisci delectus quam commodi cupiditate unde aliquam, minima eum aspernatur facere eveniet odio non quisquam, vitae quibusdam reprehenderit maxime labore doloremque, sunt. Blanditiis nisi vel modi debitis aliquid quam, amet suscipit soluta ipsam recusandae nobis consectetur nostrum dolorum necessitatibus quae quia corporis quos. Pariatur accusantium nesciunt soluta eos dignissimos aspernatur voluptatem consectetur amet perspiciatis sint!";
});

elements[1].addEventListener("click", function() {
    first.innerHTML = "Kontakt";
    second.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti voluptatum commodi sequi laudantium recusandae beatae necessitatibus cupiditate veritatis, sint, magni similique quia facilis nam voluptate consequuntur odit. Autem explicabo, deserunt nostrum ad minima unde laudantium accusantium possimus laboriosam, optio magni illum id cupiditate exercitationem enim beatae temporibus reprehenderit iusto. Laudantium minima laborum consectetur minus autem accusantium molestiae porro, architecto officiis enim iusto voluptatem dolor illo similique et unde, tenetur. Placeat dignissimos in alias quaerat non eaque sunt quisquam praesentium reprehenderit voluptatibus modi repellat eos asperiores, harum voluptate saepe neque repudiandae veniam labore, explicabo expedita cupiditate dolorem ea nobis? Vitae, unde adipisci incidunt quaerat repellendus, illum tenetur sequi. Aperiam fugiat vitae tenetur consectetur, error culpa magnam inventore eligendi ipsa repellendus, fuga doloribus earum unde dolore iusto explicabo et ut aliquam nostrum libero quia! Aspernatur consequuntur natus quos voluptas eligendi a illo placeat sit deleniti distinctio earum, sint quod quibusdam quidem odio.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum, illo! Consectetur fuga, et laudantium ea eius ex ut nemo amet, aliquid, reprehenderit tempora ab porro eum consequuntur. Doloremque reiciendis aut rerum optio praesentium. Dolores qui eius ab consequatur, totam eveniet optio rem, sit magni suscipit aspernatur esse numquam porro in minus adipisci enim impedit odio ducimus asperiores vitae facilis aliquid! Culpa distinctio eaque dignissimos temporibus odio nihil quis dicta cupiditate odit officia dolorum repellendus aliquid ad perferendis quaerat autem a nemo placeat enim quod, laudantium eveniet repellat corporis nostrum! Obcaecati eos minima nemo iusto eum molestias numquam veritatis sed, reprehenderit iste, ad praesentium non, corrupti esse adipisci porro voluptatibus magnam! Quis cumque culpa magni, eveniet tempore voluptatibus, accusantium dolore ea eos eum repudiandae debitis! Sapiente consequuntur est aperiam dicta blanditiis enim minima reprehenderit itaque voluptatibus, libero aspernatur ut ullam ab vero vel, nisi quis. Id adipisci delectus quam commodi cupiditate unde aliquam, minima eum aspernatur facere eveniet odio non quisquam, vitae quibusdam reprehenderit maxime labore doloremque, sunt. Blanditiis nisi vel modi debitis aliquid quam, amet suscipit soluta ipsam recusandae nobis consectetur nostrum dolorum necessitatibus quae quia corporis quos. Pariatur accusantium nesciunt soluta eos dignissimos aspernatur voluptatem consectetur amet perspiciatis sint!";
});

elements[2].addEventListener("click", function() {
    first.innerHTML = "O mnie";
    second.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, eos expedita nam error est veniam amet cumque optio sed! Aliquid quae totam illo sed aut ad neque dolore reprehenderit odit, adipisci velit. Excepturi magnam soluta magni quia pariatur officia. Debitis a neque explicabo, sint non.";
});

logo.addEventListener("click", function() {
    first.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia in recusandae magni dicta, neque nostrum cupiditate natus! Accusantium reprehenderit sint temporibus, iste facilis reiciendis autem eligendi nam quod, laborum quae cumque unde molestiae in qui asperiores saepe illo voluptatem tenetur eveniet! Quod sequi repellat aut, facilis, error veniam blanditiis doloremque ipsa consequatur animi porro sunt quo voluptatem reiciendis quisquam, nulla officia at illum. Sunt ab totam exercitationem aliquid voluptatibus quidem, ipsa ea vero eius repellat tempora culpa nemo inventore ipsum. Distinctio saepe quisquam in vitae magni excepturi vero et laborum. Molestiae quibusdam aperiam cupiditate deleniti tempore rerum tenetur quae maiores.";
    second.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi esse sequi quibusdam, non quo quia iure tempore praesentium adipisci deleniti! Dolore autem atque iste reiciendis sit accusantium similique consectetur in vitae architecto, error quis explicabo itaque, facere, nam libero, sequi iure. Sed alias libero veniam officia amet expedita, praesentium laboriosam natus saepe impedit consequuntur vel deserunt esse sint optio nobis, nemo voluptate nisi laudantium cupiditate? Dolore officiis veniam atque cupiditate, aperiam minus culpa, quisquam, nemo ratione debitis laborum natus repellat eos! Et excepturi error, natus unde adipisci officiis eos magnam dolores quia totam, odio vero quae. Culpa sed architecto alias natus perferendis debitis ut incidunt, esse quae asperiores enim eaque eius ad aliquid fugit dolorem quidem voluptatum rem iste atque eveniet illo nobis saepe commodi veniam. Hic nostrum facilis, tenetur quia laboriosam magni sunt quam amet dolorem distinctio explicabo suscipit quos molestias! Rerum optio repellat recusandae numquam iusto labore quidem similique, pariatur, mollitia accusantium officiis eligendi fuga, dolorem suscipit libero adipisci sequi perferendis excepturi soluta consectetur enim voluptatum quam eveniet voluptatem. Quisquam in natus laborum placeat, unde repellendus officia beatae. Possimus a accusamus sunt officia molestias alias aut, officiis fugit animi repudiandae porro harum laudantium voluptas ducimus quae veritatis nemo?";
});
